### ISSUE TITLE
Report raises Encoding::UndefinedConversionError

### ISSUE THREAD

**Issue by afriqs** [pact-foundation/pact-ruby#230] opened 2020-11-30 15:22 UTC
Hi,

Just upgrading an old app and I encountered the following issue : 
```ruby
An error occurred in an `after(:suite)` hook.
Failure/Error: File.open(help_path, "w") { |file| file << help_text }

Encoding::UndefinedConversionError:
  "\xC3" from ASCII-8BIT to UTF-8
# ./vendor/bundle/ruby/2.6.0/gems/pact-1.43.1/bin/pact:4:in `<top (required)>'
# ./vendor/bundle/ruby/2.6.0/bin/pact:23:in `load'
# ./vendor/bundle/ruby/2.6.0/bin/pact:23:in `<main>'
```

It seems it was introduced in `1.43.0`.

Thanks.

**Comment by bethesque** [comment] 2020-11-30 21:57
Can you identify which interaction causes it? 
If you run the suite with BACKTRACE=true it should give you more info in the callstack.

**Comment by afriqs** [comment] 2020-12-01 09:53
It happens with any set of pacts if I well understand your question.

Here is the full callstask : 
```ruby
An error occurred in an `after(:suite)` hook.
Failure/Error: File.open(help_path, "w") { |file| file << help_text }

Encoding::UndefinedConversionError:
  "\xC3" from ASCII-8BIT to UTF-8
# ./vendor/bundle/ruby/2.7.0/gems/pact-1.55.7/lib/pact/provider/help/write.rb:41:in `write'
# ./vendor/bundle/ruby/2.7.0/gems/pact-1.55.7/lib/pact/provider/help/write.rb:41:in `<<'
# ./vendor/bundle/ruby/2.7.0/gems/pact-1.55.7/lib/pact/provider/help/write.rb:41:in `block in write'
# ./vendor/bundle/ruby/2.7.0/gems/pact-1.55.7/lib/pact/provider/help/write.rb:41:in `open'
# ./vendor/bundle/ruby/2.7.0/gems/pact-1.55.7/lib/pact/provider/help/write.rb:41:in `write'
# ./vendor/bundle/ruby/2.7.0/gems/pact-1.55.7/lib/pact/provider/help/write.rb:23:in `call'
# ./vendor/bundle/ruby/2.7.0/gems/pact-1.55.7/lib/pact/provider/help/write.rb:13:in `call'
# ./vendor/bundle/ruby/2.7.0/gems/pact-1.55.7/lib/pact/provider/pact_spec_runner.rb:84:in `block in configure_rspec'
# ./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.0/lib/rspec/core/example.rb:455:in `instance_exec'
# ./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.0/lib/rspec/core/example.rb:455:in `instance_exec'
# ./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.0/lib/rspec/core/hooks.rb:372:in `run'
# ./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.0/lib/rspec/core/configuration.rb:2144:in `block in run_suite_hooks'
# ./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.0/lib/rspec/core/configuration.rb:2142:in `each'
# ./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.0/lib/rspec/core/configuration.rb:2142:in `run_suite_hooks'
# ./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.0/lib/rspec/core/configuration.rb:2069:in `with_suite_hooks'
# ./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.0/lib/rspec/core/runner.rb:116:in `block in run_specs'
# ./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.0/lib/rspec/core/reporter.rb:74:in `report'
# ./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.0/lib/rspec/core/runner.rb:115:in `run_specs'
# ./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.0/lib/rspec/core/runner.rb:89:in `run'
# ./vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.0/lib/rspec/core/runner.rb:71:in `run'
# ./vendor/bundle/ruby/2.7.0/gems/pact-1.55.7/lib/pact/provider/pact_spec_runner.rb:90:in `run_specs'
# ./vendor/bundle/ruby/2.7.0/gems/pact-1.55.7/lib/pact/provider/pact_spec_runner.rb:35:in `run'
# ./vendor/bundle/ruby/2.7.0/gems/pact-1.55.7/lib/pact/cli/run_pact_verification.rb:76:in `run_with_configured_pacts_from_pact_helper'
# ./vendor/bundle/ruby/2.7.0/gems/pact-1.55.7/lib/pact/cli/run_pact_verification.rb:53:in `run_specs'
# ./vendor/bundle/ruby/2.7.0/gems/pact-1.55.7/lib/pact/cli/run_pact_verification.rb:21:in `call'
# ./vendor/bundle/ruby/2.7.0/gems/pact-1.55.7/lib/pact/cli/run_pact_verification.rb:13:in `call'
# ./vendor/bundle/ruby/2.7.0/gems/pact-1.55.7/lib/pact/cli.rb:31:in `verify'
# ./vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
# ./vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
# ./vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
# ./vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
# ./vendor/bundle/ruby/2.7.0/gems/pact-1.55.7/bin/pact:4:in `<top (required)>'
# ./vendor/bundle/ruby/2.7.0/bin/pact:23:in `load'
# ./vendor/bundle/ruby/2.7.0/bin/pact:23:in `<main>'
```

Hope it helps :relaxed:

**Comment by bethesque** [comment] 2020-12-02 06:25
I think there must be a non utf-8 character in the diff

```
require 'pact/provider/help/pact_diff'

module Pact
  module Provider
    module Help
      class Content

        def initialize pact_sources
          @pact_sources = pact_sources
        end

        def text
          help_text + "\n\n" + pact_diffs
        end

        private

        attr_reader :pact_sources

        def help_text
          temp_dir = Pact.configuration.tmp_dir
          log_path = Pact.configuration.log_path
          ERB.new(template_string).result(binding)
        end

        def template_string
          File.read(File.expand_path( '../../../templates/help.erb', __FILE__))
        end

        def pact_diffs
          pact_sources.collect do | pact_json |
            PactDiff.call(pact_json)
          end.compact.join("\n")
        end
      end
    end
  end
end
```

Are you running this on windows? Can you try setting your default encoding to utf-8 as per https://stackoverflow.com/questions/5908774/set-global-default-encoding-for-ruby-1-9

**Comment by afriqs** [comment] 2020-12-08 15:57
I'm running GNU/Linux and this is weird. I identified the culprit pact.
```shell
$ file -bi pacts/my_pact.json 
text/plain; charset=utf-8
```
When I check the pact from the pact-broker instance I have the error message : 
```ruby
$ bundle exec rake pact:verify:at[https://domain.tld/pacts/provider/my_provider/consumer/consumer-my_pact/latest]
[...]
An error occurred in an `after(:suite)` hook.
Failure/Error: File.open(help_path, "w") { |file| file << help_text }

Encoding::UndefinedConversionError:
  "\xC3" from ASCII-8BIT to UTF-8
# ./vendor/bundle/ruby/2.6.0/gems/pact-1.55.7/bin/pact:4:in `<top (required)>'
# ./vendor/bundle/ruby/2.6.0/bin/pact:23:in `load'
# ./vendor/bundle/ruby/2.6.0/bin/pact:23:in `<main>'

8 interactions, 0 failures
```
When I check the pact from the filesystem I don't : 
```ruby
$ be rake pact:verify:at[my_pact.json]
[...]
8 interactions, 0 failures
```
And I have the issue with `RUBYOPT='-E utf-8' bundle exec rake pact:verify:at[https://domain.tld/pacts/provider/my_provider/consumer/consumer-my_pact/latest]`

Still investigating... :thinking:

**Comment by bethesque** [comment] 2020-12-08 21:29
Are you able to reproduce it on a docker container so I can investigate it locally? I'm afraid there's not much I can do until I have a repro. Here's a docker compose file that contains a pact broker and a publication/verification task https://github.com/pact-foundation/pact-ruby-e2e-example/blob/feat/docker-compose/docker-compose.yml

**Comment by afriqs** [comment] 2020-12-09 09:54
We don't use docker (inside lxc container) but I will try on my laptop (not used to using docker).

Moreover I upgraded our *pact-broker* to `2.72.0.0` and the issue is still present. :sweat:

**Comment by bethesque** [comment] 2020-12-10 20:08
If you're up for a bit of hacking, you would try using BACKTRACE=true to find the actual location of the error, and then modify the ruby code to force the encoding to UTF8. It is a lossy conversion though, and doesn't help us identify exactly what is causing the failure 

https://stackoverflow.com/questions/12947910/force-strings-to-utf-8-from-any-encoding

**Comment by bethesque** [comment] 2021-01-21 05:32
Any progress?

**Comment by afriqs** [comment] 2021-01-21 12:42
No, sorry, I didn't have time to work on it. You can close the issue if you will, I will work on it someday though.

**Comment by bethesque** [comment] 2021-01-21 22:16
It looks like it was this commit that changed it.

commit b9deb09d857bcaacb0e8d97c00701e24aa35e2c3
Author: Beth Skurrie <beth@bethesque.com>
Date:   Sat Jan 11 19:14:15 2020 +1100

    fix: use configured credentials when fetching the diff with previous version

    Closes: https://github.com/pact-foundation/pact-ruby/issues/205

It previously wasn't using any credentials, so I think it just errored silently because it didn't get a response.

I've put out a new release which catches and logs any errors during the help text generation. It won't fix it, but it at least it won't make the hooks error.

**Closed by bethesque** 2021-01-21 22:16 UTC
